### ISSUE TITLE
CRUD to listings

### ISSUE THREAD

**Issue by mirrenil** [mirrenil/arbetsmetodik#128]
Som användare vill jag kunna ta bort eller ändra något i mina annonser.

Acceptanskrav:

- [ ] Användare ska kunna ändra datan på annonser.

- [ ]  Användaren ska kunna ta bort en annons

**Comment by hazem-89** [comment]
is the same issue as #111 https://github.com/mirrenil/arbetsmetodik/issues/111 ??

**Comment by mirrenil** [comment]
Omg yes Im super blind
